---
- name: Create docker volume for grafana
  docker_volume:
    name: docker_grafana-data

- name: Create grafana container
  docker_container:
    name: grafana-1
    image: grafana/grafana:latest
    pull: true
    restart_policy: always
    volumes:
      - docker_grafana-data:/var/lib/grafana
    networks:
      - name: docker_backend
        aliases:
          - grafana
    etc_hosts:
      host.docker.internal: "{{ docker_network.network.IPAM.Config[0].Gateway }}"
