---
- name: Setup server
  hosts: all
  become: true
  roles:
    - role: common
    - role: fail2ban
    - role: fail2ban_exporter
      tags: fail2ban_exporter
    - role: ohmyposh
    - role: docker
    - role: firewall
    - role: haproxy
      tags: haproxy
    - role: docker_network
      tags: docker_network
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana
    - role: vaultwarden
      tags: vaultwarden
