---
- hosts: all
  become: true
  roles:
    - role: common
    - role: fail2ban
    - role: fail2ban-exporter
      tags: fail2ban-exporter
    - role: ohmyposh
    - role: docker
    - role: firewall
    - role: haproxy
      tags: haproxy
    - role: docker-network
      tags: docker-network
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana
    - role: vaultwarden
      tags: vaultwarden
