---
- name: Install unzip
  apt:
    name: unzip
    state: latest

- name: Check if oh-my-posh is installed in /usr/local/bin
  stat:
    path: /usr/local/bin/oh-my-posh
  register: oh_my_posh_bin

- name: Download oh-my-posh
  get_url:
    url: https://ohmyposh.dev/install.sh
    dest: /tmp/install.sh
    mode: "0755"
  when: not oh_my_posh_bin.stat.exists

- name: Install oh-my-posh
  command: /tmp/install.sh
  when: not oh_my_posh_bin.stat.exists

- name: Create oh-my-posh config directory
  file:
    path: /home/{{ ansible_user }}/.oh-my-posh/custom
    state: directory

- name: Copy oh-my-posh config
  copy:
    src: tokyo.omp.json
    dest: /home/{{ ansible_user }}/.oh-my-posh/custom/tokyo.omp.json

- name: Add oh-my-posh to bashrc
  lineinfile:
    dest: /home/{{ ansible_user }}/.bashrc
    line: eval "$(oh-my-posh init bash --config ~/.oh-my-posh/custom/tokyo.omp.json)"
    state: present
