---
- name: Install ca-certificates and curl
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.asc

- name: Set file permissions on Docker GPG apt key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  register: add_repo

- name: Update apt cache
  when: add_repo.changed
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Docker prune
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
  changed_when: false
