---
name: ansible-lint

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint ansible
      - name: Lint code and output stout to a file
        run: |
          ansible-lint &> ansible-lint.txt
        continue-on-error: true
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ansible-lint.txt
          comment_tag: ansible-lint
